import type { Invoice } from "../types/transaction";
import { formatPaise, formatDate } from "../lib/format";

interface InvoicePreviewProps {
  invoice: Invoice;
  invoiceNumber?: number;
}

export function InvoicePreview({
  invoice,
  invoiceNumber = 1,
}: InvoicePreviewProps) {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div>
      {/* Print-only styles injected via a style tag */}
      <style>{`
        @media print {
          body > *:not(#invoice-print-root) { display: none !important; }
          #invoice-print-root { display: block !important; }
          .no-print { display: none !important; }
        }
      `}</style>

      <div
        id="invoice-print-root"
        className="bg-surface border border-border rounded-xl p-6 shadow-sm"
      >
        {/* Header */}
        <div className="flex items-start justify-between mb-6">
          <div>
            <h1 className="font-display text-2xl font-bold text-primary">
              VaniBooks
            </h1>
            <p className="text-xs text-muted font-body">Tax Invoice</p>
          </div>
          <div className="text-right">
            <p className="font-mono text-sm font-semibold text-text">
              #{String(invoiceNumber).padStart(4, "0")}
            </p>
            <p className="text-xs text-muted font-body">
              {formatDate(invoice.date)}
            </p>
          </div>
        </div>

        {/* Client */}
        <div className="mb-6 p-3 bg-bg rounded-lg">
          <p className="text-xs text-muted font-body mb-1">Bill To</p>
          <p className="font-body font-semibold text-text">
            {invoice.clientName}
          </p>
        </div>

        {/* Items table */}
        <table className="w-full text-sm font-body mb-4">
          <thead>
            <tr className="border-b-2 border-primary/20">
              <th className="text-left py-2 text-muted font-medium text-xs">
                Item
              </th>
              <th className="text-center py-2 text-muted font-medium text-xs">
                Qty
              </th>
              <th className="text-right py-2 text-muted font-medium text-xs">
                Price
              </th>
              <th className="text-right py-2 text-muted font-medium text-xs">
                Total
              </th>
            </tr>
          </thead>
          <tbody>
            {invoice.items.map((item, i) => (
              <tr key={i} className="border-b border-border">
                <td className="py-2.5 text-text">{item.name}</td>
                <td className="py-2.5 text-center text-muted">
                  {item.quantity}
                </td>
                <td className="py-2.5 text-right font-mono text-muted">
                  {formatPaise(item.pricePaise)}
                </td>
                <td className="py-2.5 text-right font-mono text-text font-medium">
                  {formatPaise(item.totalPaise)}
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {/* Totals */}
        <div className="ml-auto max-w-[200px] space-y-1.5 text-sm font-body">
          <div className="flex justify-between text-muted">
            <span>Subtotal</span>
            <span className="font-mono">{formatPaise(invoice.subtotalPaise)}</span>
          </div>
          <div className="flex justify-between text-muted">
            <span>GST ({invoice.gstRatePct}%)</span>
            <span className="font-mono">
              {formatPaise(invoice.gstAmountPaise)}
            </span>
          </div>
          <div className="flex justify-between font-semibold text-text border-t border-border pt-1.5">
            <span>Total</span>
            <span className="font-mono text-accent">
              {formatPaise(invoice.totalAmountPaise)}
            </span>
          </div>
        </div>

        {/* Footer */}
        <p className="mt-6 text-xs text-muted font-body text-center">
          Generated by VaniBooks Lite · Thank you for your business
        </p>
      </div>

      {/* Actions */}
      <div className="flex gap-2 mt-3 no-print">
        <button
          onClick={handlePrint}
          className="flex-1 border border-border text-text text-sm font-body font-medium py-2 rounded-lg hover:bg-bg transition-colors"
        >
          Print / Download PDF
        </button>
      </div>
    </div>
  );
}
